### ISSUE TITLE
Declare build dependencies in pyproject.toml

### ISSUE THREAD

**Issue by mdickinson** [enthought/scimath#76]
scimath requires `numpy` in order to build, which means that a plain `pip install scimath` in an otherwise bare environment (+ pip, setuptools) will fail with something like this:
```
(scimath)bash-3.2$ pip install scimath
Collecting scimath
  Downloading https://files.pythonhosted.org/packages/fc/cf/cae77166021b4624a503656e0ba0423fc948c6615c997ec931b2c2e951e2/scimath-4.2.0.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 5.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/pip-install-h1q74gmd/scimath/setup.py", line 8, in <module>
        import numpy.distutils.core
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/pip-install-h1q74gmd/scimath/

```

Modern `pip` allows for a `pyproject.toml` file to specify build dependencies. See https://github.com/enthought/ibm2ieee/blob/master/pyproject.toml for an example. Assuming that the NumPy build dependency is needed here, we could add a `pyproject.toml` file here.

**Comment by mdickinson** [comment]
Looks like #79 needs to be fixed first, so that we have a MANIFEST.in to add the `pyproject.toml` file to.
